# **Código de conducta de la comunidad**

**Nuestro compromiso**

Nosotros, como editores, miembros colaboradores y líderes, nos comprometemos a hacer de la participación en nuestra comunidad sea una experiencia libre de acoso para todos, independientemente de la edad, el tamaño discapacidad visible o invisible, origen étnico, características sexuales, identidad y expresión de identidad y expresión de género, nivel de experiencia, educación, estatus socioeconómico nacionalidad, apariencia personal, raza, religión o identidad y orientación sexual. y orientación sexual.

Nos comprometemos a actuar e interactuar de manera que contribuya a una comunidad abierta, acogedora diversa, inclusiva y saludable.

**Nuestras normas**

Ejemplos de comportamientos que contribuyen a un entorno positivo para nuestra comunidad incluyen:

-   Demostrar empatía y amabilidad hacia los demas.

-   Ser respetuoso con las diferentes opiniones, puntos de vista y experiencias.

-   Dar y aceptar con gracia comentarios productivos.

-   Aceptar la responsabilidad y pedir disculpas a los afectados por nuestros errores, y aprender de la experiencia.

-   Centrarse en lo que es mejor no sólo para nosotros como individuos, sino para la comunidad en general.

-   Trabajar con transparencia.

-   Respetar las diferencias étnicas, el idioma y la cultura de quienes forman parte de la comunidad.

-   Proporcionar apoyo logístico a los nuevos editores.

-   Participar activamente en la comunidad.

-   Ayudar a mantener el control en situaciones controvertidas.

-   Respetar las normas de la comunidad.

-   Respetar los horarios de descanso laboral (Solo se podrá enviar y responder información a whatsapp , telegram y discord en horario laboral (18:00 pm a 00:00 am), en especial envió y recibo de correos oficiales a los coordinadores, colaboradores y estudiantes ) Excepciones: Se podrá enviar un correo fuera de horario laboral por parte de cualquier persona de la comunidad, pero siempre aclarando que la persona a la que se envió el mensaje pueda responderlo en horario laboral, y no en descanso laboral, respetando su privacidad y descanso.

Algunos ejemplos de comportamiento inaceptable son:

-   Usar lenguaje o imágenes sexualizadas, y la atención sexual o insinuaciones sexuales de cualquier tipo.

-   Trolling, comentarios insultantes o despectivos, y ataques personales o políticos.

-   Acoso público o privado.

-   Publicar información privada de otros, como su dirección física o de correo electrónico, sin su permiso explícito. Publicar información privada de otros, como una dirección física o de correo electrónico, sin su permiso explícito.

-   Demostrar conductas que puedan considerarse razonablemente inapropiadas en un entorno profesional.

-   Demostrar un comportamiento reactivo ante una retroalimentación.

-   Perjudicar el crecimiento o el desarrollo profesional de cualquier miembro en el ámbito editorial o de investigación.

-   Incumplir las normas éticas editoriales y de investigación.

-   Realizar SPAM (comunicaciones no solicitadas que se envían de forma masiva).

-   Realizar publicidad o enviar enlaces de cualquier tipo no relacionados a la mision y vision de la comunidad, sin autorizacion.

**Responsabilidades de los coordinadores**

Los coordinadores son responsables de aclarar y hacer cumplir nuestras normas de comportamiento aceptable y tomarán medidas correctivas apropiadas y justas en respuesta a cualquier comportamiento que consideren inapropiado, amenazante, ofensivo o perjudicial.

Los coordinadores tienen el derecho y la responsabilidad de eliminar, editar o rechazar comentarios, commits, código, ediciones de la wiki, cuestiones y otras contribuciones que que no se ajusten a este Código de Conducta, y comunicarán las razones de las decisiones de moderación decisiones de moderación cuando sea apropiado.

**Alcance**

Este Código de Conducta se aplica en todos los espacios de la comunidad, y también se aplica cuando un individuo representa oficialmente a la comunidad en espacios públicos. Ejemplos de representación de nuestra comunidad incluyen el uso de una dirección de correo electrónico oficial, publicar a través de una cuenta oficial en las redes sociales, o actuar como representante representante en un evento en línea o fuera de línea.

**Aplicación de la ley**

Los casos de comportamiento abusivo, acosador o inaceptable pueden ser denunciarse a los coordinadores de la comunidad responsables de su aplicación.

Todas las quejas serán revisadas e investigadas de forma rápida y justa.

Todos los coordinadores de la comunidad están obligados a respetar la privacidad y la seguridad del denunciante de cualquier incidente.

**Directrices de comunidad**

Los coordinadores seguirán estas Directrices de Impacto Comunitario para determinar las consecuencias de cualquier acción que consideren que infringe este Código de Conducta:

### **1. Corrección**

**Impacto en la comunidad**: El uso de un lenguaje inapropiado u otro comportamiento considerado poco profesional o inoportuno en la comunidad.

**Consecuencia**: Una advertencia privada y por escrito de los líderes de la comunidad, proporcionando claridad en torno a la naturaleza de la infracción y una explicación de por qué el comportamiento fue inapropiado. Puede solicitarse una disculpa pública.

### **2. Advertencia**

**Impacto en la comunidad**: Una violación a través de un solo incidente o una serie de acciones.

**Consecuencia**: Una advertencia con consecuencias para el comportamiento continuado. No interacción con las personas implicadas, incluida la interacción no solicitada con con los encargados de hacer cumplir el Código de Conducta, durante un periodo de tiempo determinado. Este incluye evitar las interacciones en los espacios de la comunidad, así como en los canales externos como las redes sociales. La violación de estas condiciones puede dar lugar a una prohibición temporal o permanente.

### **3. Prohibición temporal**

**Impacto en la comunidad**: Una violación grave de las normas de la comunidad, incluyendo comportamiento inapropiado sostenido.

\*\*Consecuencia: Prohibición temporal de cualquier tipo de interacción o comunicación comunicación pública con la comunidad durante un período de tiempo determinado. Se prohíbe la interacción pública o privada con las personas involucradas, incluyendo la interacción no solicitada con los encargados de hacer cumplir el Código de Conducta,no está permitida durante este periodo. La violación de estos términos puede llevar a un baneo permanente.

### **4. Prohibición permanente**

**Impacto en la comunidad**: Demostrar un patrón de violación de las normas de la comunidad, incluyendo un comportamiento inapropiado sostenido, acoso a un individuo, o la agresión hacia o el desprecio de clases de individuos.

\*\*Consecuencia: Prohibición permanente de cualquier tipo de interacción pública dentro de la comunidad.

## **Atribución**

Las Directrices de Impacto Comunitario se inspiraron en [el código de conducta de Mozilla de Mozilla] (<https://github.com/mozilla/diversity>).

\









